 import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/Nav";
import Sidebar from "@/components/sidebar/Sidebar";
import { Tabs } from "@/components/tabs/Tabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="h-14 md:h-10 ">
            <Nav />
          </div>
          <div className="flex  h-[calc(100vh-2.5rem)] bg-secondary ">
            <div className="h-full bg-slate-400">
              <Sidebar />
            </div>
            <div className="flex flex-col size-full">
              <div>
                <Tabs />
              </div>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
